# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Estafeta-1"
client_id = "9618453d1fdc8d80dc7f2bd25dcc89a5"
application_url = "https://wax-able-unity-tramadol.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://wax-able-unity-tramadol.trycloudflare.com/auth/callback",
  "https://wax-able-unity-tramadol.trycloudflare.com/auth/shopify/callback",
  "https://wax-able-unity-tramadol.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "estafeta-shop-test.myshopify.com"
