# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Estafeta"
client_id = "228f9b3648e05552580fc62e32cd8b1f"
application_url = "https://avenue-functions-pm-r.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://avenue-functions-pm-r.trycloudflare.com/auth/callback",
  "https://avenue-functions-pm-r.trycloudflare.com/auth/shopify/callback",
  "https://avenue-functions-pm-r.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "estafeta-plug-in.myshopify.com"
