# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "prueba-1001-estafeta"
client_id = "90f89903b29be602b55d4ecf1e62bdbe"
application_url = "https://panel-geo-danger-desktops.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://panel-geo-danger-desktops.trycloudflare.com/auth/callback",
  "https://panel-geo-danger-desktops.trycloudflare.com/auth/shopify/callback",
  "https://panel-geo-danger-desktops.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tienda-pruebas-estafeta.myshopify.com"
